---
version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/work
    #machine:
    #  image: circleci/classic:latest
    docker:
      - image: ubuntu:18.04

    steps:
      - run: &apt_install
          apt update &&
          export DEBIAN_FRONTEND=noninteractive ; apt install -y --no-install-recommends
            cmake
            gcc g++
            libconfig-dev
            libgtest-dev
            ninja-build
            pkg-config
            zip grep file ca-certificates autotools-dev autoconf automake
            git bc wget rsync cmake make pkg-config libtool
            ssh gzip tar unzip
            libcurl4-gnutls-dev
            coreutils

      - checkout

      - run: pwd; ls -al
      - run: cd circle_scripts/ && bash do_it_linux.sh


      #- store_artifacts:
      #    path: ~/work/artefacts
      #    destination: artefacts
